[project]
name = "fizzbuzz"
version = "0.1.0"
requires-python = ">=3.10"

[project.scripts]
fizzbuzz = "fizzbuzz:main"

[project.optional-dependencies]
dev = ["pytest", "pytest-randomly", "pytest-watch"]
